package com.angaihouse.utils;
import java.util.ArrayList;

public class Constants {
    public static final String URL = "https://tofiko.com/";
    public static final String STRIPE_KEY = "pk_live_hqbv05KP6UzG5lg7fZL3Cjrb00tWU1AXfd";
    public static final String DEVICE_TYPE = "android";
    public static int DONT_ALLOW_PERMISSION = 0;
    public static String COMPANY_ID = "1";

    public static final String USER_ID = "USER_ID";

    public static String CATEGORY_ID = "";

    public static String COLLECT_HERE = "COLLECT_HERE";

    public static String ADDRESS_LINE_2 = "ADDRESS_LINE_2";
    public static final String CURRENCY = "CURRENCY";
    public static final String NEAR_RES_ID = "NEAR_RES_ID";
    public static final String MENU_SEARCH = "MENU_SEARCH";
    public static final String USER_FNAME = "USER_FNAME";
    public static final String USER_LNAME = "USER_LNAME";
    public static final String USER_DOB = "USER_DOB";
    public static final String COUNTRY_CODE = "COUNTRY_CODE";
    public static final String ITEM_GRID = "ITEM_GRID";
    public static final String mobile_no = "mobile_no";
    public static final String email = "email";
    public static final String password = "password";
    public static final String gender = "gender";
    public static final String address = "address";
    public static final String address1 = "address1";
    public static final String province = "province";
    public static final String city = "city";
    public static final String country = "country";
    public static final String zipcode = "zipcode";
    public static final String company_name = "company_name";
    public static final String company_legal_email = "company_legal_email";
    public static final String company_id = "company_id";
    public static final String unique_invoicing_code = "unique_invoicing_code";
    public static final String vat_id = "vat_id";
    public static final String image = "image";
    public static final String type = "type";
    public static final String USER_LAT = "USER_LAT";
    public static final String USER_LNG = "USER_LNG";
    public static final String CART_ID = "CART_ID";
    public static final String ORDER_TYPE = "ORDER_TYPE";
    public static final String USER_FCM = "USER_FCM";
    public static final String CUST_ID = "CUST_ID";
    public static final String REFERRAL_CODE = "REFERRAL_CODE";
    public static final String ORDER_PUSH_NOTIFICATION = "ORDER_PUSH_NOTIFICATION";
    public static final String NEWS_PUSH_NOTIFICATION = "NEWS_PUSH_NOTIFICATION";
    public static final String ORDER_EMAIL_NOTIFICATION = "ORDER_EMAIL_NOTIFICATION";
    public static final String NEWS_EMAIL_NOTIFICATION = "NEWS_EMAIL_NOTIFICATION";
    public static final String TOKEN = "TOKEN";
    public static final String APP_LANGUAGE = "APP_LANGUAGE";
    public static final String GUEST_LOGIN = "GUEST_LOGIN";

    public static final String referral_msg = "referral_msg";
    public static final String tofiko_url = "tofiko_url";

    public static final String FB_URL = "FB_URL";
    public static final String INSTA_URL = "INSTA_URL";
    public static final String MANGAL_URL = "MANGAL_URL";
    public static final String YOUTUBE_URL = "YOUTUBE_URL";
    public static final String TELEGRAM_URL = "TELEGRAM_URL";
    public static final String INSTA_IMAGE = "INSTA_IMAGE";
    public static String LAT_STRING = "LAT_STRING";
    public static String LNG_STRING = "LNG_STRING";
    public static String DAY = "DAY";
    public static double latitude = -99.99;
    public static double longitude = -99.99;

    public static  String terms = "terms";
    public static String policy= "policy";
    public static String cookie= "cookie";
    public static String offer_banner= "offer_banner";
    public static String youtube_channel= "youtube_channel";
    public static String mangal_link= "mangal_link";
    public static String facebook_channel= "facebook_channel";
    public static String instagram_channel= "instagram_channel";
    public static String telegram_channel= "telegram_channel";
    public static String facebook_share= "facebook_share";
    public static String instagram_share= "instagram_share";
    public static String linkedin_share= "linkedin_share";
    public static String whatsapp_share= "whatsapp_share";
    public static String telegram_share= "telegram_share";
    public static String where_we_are= "where_we_are";
    public static String about_us= "about_us";
    public static String invite_friends= "invite_friends";


    public static String BANNER_DELIVERY_TYPE= "BANNER_DELIVERY_TYPE";
    public static String BANNER_ADDRESS_ID= "BANNER_ADDRESS_ID";


    public static String NOTIFICATION_DETAIL="NOTIFICATION_DETAIL";
    public static String NO_NOTIFICATIONS_AVAILABLE="NO_NOTIFICATIONS_AVAILABLE";



    ///Language Keyword String
    public static String LOGIN;
    public static String DELIVERY;
    public static String ORDER_TYPE_K;
    public static String TAKEAWAY_FROM_STORE;
    public static String SELECT_ADDRESS;
    public static String HOW_WOULD_LIKE;
    public static String RECEIVE_ORDER;
    public static String LIKE_MANGAL;
    public static String SHARE_WITH_FRIENDS;
    public static String INVITE_DESCRIPTION;
    public static String TAKEAWAY;
    public static String SIGN_UP;
    public static String EMAIL_ADDRESS;
    public static String YOUR_CART_EMPTY;
    public static String BACK_MAIN_MENU;
    public static String PAY_WITH_MANGAL;
    public static String PROVIDE_TERMS_CONDITION;
    public static String ITEM_TOTAL;
    public static String PASSWORD;
    public static String FORGOT_PASS;
    public static String ORDER_FROM_MENU;
    public static String CREATE_AC;
    public static String BY_LOGIN_TERMS_CONDITION_LABEL;
    public static String SEND_PASS;
    public static String GENDER;
    public static String MALE;
    public static String FEMALE;
    public static String FNAME;
    public static String LNAME;
    public static String PHONE_NUMBER;
    public static String DOB;
    public static String CHOOSE_TEST;
    public static String COOKING_LEVEL;
    public static String ADD_EXTRA;
    public static String WANT_TO_REMOVE;
    public static String APPLY_CHANGES;
    public static String PH_NUMBER;
    public static String CONFIRM_PASS;
    public static String ALREADY_AC_LABEL;
    public static String REFERRAL_CODE_EXIST;
    public static String I_AGREE;
    public static String LOGIN_FLOW;
    public static String SET_PASSWORD;
    public static String ENTER_COMPANY_INFO;
    public static String NEXT;
    public static String DELIVERY_INFO;
    public static String BACK;
    public static String TYPE;
    public static String PRIVATE;
    public static String COMPANY;
    public static String ADDRESS;
    public static String PROVINCE;
    public static String CITY;
    public static String COUNTRY;
    public static String ZIPCODE;
    public static String ADD_INVOICE;
    public static String COMPANY_INFO;
    public static String COMPANY_NAME;
    public static String VAT_ID;
    public static String LEGAL_EMAIL;
    public static String INVOICE_CODE;
    public static String TERMS_CONDITION_LABEL;
    public static String REGISTER;
    public static String WITHOUT_LOGIN;
    public static String SIGN_AGREEMENT;
    public static String INVITE_FRIENDS_DESC;
    public static String SHARE_CODE;
    public static String INVITE_FRIENDS_LABEL;
    public static String MY_ORDER_HISTORY;
    public static String SHARE_FB_INSTA_DESC;
    public static String CONTACT_NO;
    public static String MESSAGE;
    public static String SHARE;
    public static String CONTACT_US;
    public static String SUBMIT;
    public static String DELIVERY_ADDRESS;
    public static String DOOR_NO;
    public static String ADDRESS_LINE;
    public static String HOME;
    public static String CONTINUE;
    public static String LANGUAGE;
    public static String WORK;
    public static String OTHER;
    public static String SAVE;
    public static String RES_NAME;
    public static String PAYMENT;
    public static String NAME_OF_PERSON;
    public static String MOBILE_NO;
    public static String RES_NUMBER;
    public static String GUEST_ERROR;
    public static String TOTAL_PAYABLE;
    public static String QTY;
    public static String DELIVERY_CHARGE;
    public static String TOTAL;
    public static String CHOOSE_DELIVERY_TIME;
    public static String CREDIT_DEBIT_CARD;
    public static String LATER;
    public static String ADD_NEW_CARD;
    public static String COD;
    public static String KEEP_CASH_ON_HAND;
    public static String PAY_ON_DELIVERY;
    public static String ORDER;
    public static String PAYPAL;
    public static String PAY_VIA_PAYPAL;
    public static String ORDER_PLACED;
    public static String THANK_YOU;
    public static String ORDER_PLACED_SUCCESS;
    public static String GO_TO_HOME;
    public static String ADD_CARD;
    public static String CARD_TYPE;
    public static String CARD_NUMBER;
    public static String EXPIRY_DATE;
    public static String CVV_CODE;
    public static String SELECT_CARD_TYPE;
    public static String ENTER_CARD_NUMBER;
    public static String MONTH;
    public static String YEAR;
    public static String CONTACT_SUPPORT;
    public static String FAQ;
    public static String STILL_QUESTIONS;
    public static String ASKED_QUE;
    public static String ADD;
    public static String SEE_MORE;
    public static String MY_MANGAL_POINT;
    public static String SEARCH_PRODUCT;
    public static String INGREDIENTS;
    public static String ORDER_HISTORY;
    public static String PENDING;
    public static String IN_PREPARE;
    public static String COMPLETED;
    public static String TRANSACTION_ID;
    public static String REPEAT_ORDER;
    public static String ORDER_DATE;
    public static String ORDER_AMOUNT;
    public static String FEEDBACK;
    public static String RATING;
    public static String ADD_COMMENT;
    public static String WOOPS;
    public static String CART_EMPTY;
    public static String CUSTOMIZABLE;
    public static String CART;
    public static String SPECIAL_REQUEST;
    public static String SPECIAL_OFFERS;
    public static String WHERE_WE_ARE;
    public static String CUSTOMER_SERVICE;
    public static String CHECKOUT;
    public static String PUSH_NOTIFICATION;
    public static String ORDER_DETAIL;
    public static String N;
    public static String A;
    public static String M;
    public static String TYPE_OF_PAYMENT;
    public static String ABOUT_US;
    public static String MY_ACCOUNT;
    public static String SETTING;
    public static String VERSION;
    public static String EDIT_PROFILE;
    public static String UPDATE;
    public static String PRIVACY_POLICY;
    public static String COOKIES;
    public static String MY_CART;
    public static String MY_MANGALS;
    public static String AVAILABLE_OFFERS;
    public static String RES_DETAIL;
    public static String INFO;
    public static String GALLERY;
    public static String REVIEW;
    public static String ADD_TO_CART;
    public static String ADD_TO_FAVOURITE;
    public static String NOT_AVAILABLE_FOR_ORDER;
    public static String FAVOURITE;
    public static String LOCATE_ON_MAP;
    public static String LIST_OF_ALLERGENS;
    public static String RES_REVIEW;
    public static String RES_INFO;
    public static String SHARE_AND_EARN;
    public static String LOGOUT;
    public static String VAILD_EMAIL;
    public static String PROVIDE_PASS;
    public static String PROVIDE_EMAIL;
    public static String CHECK_INTERNET;
    public static String PROVIDE_PROFILE_IMG;
    public static String PROVIDE_FNAME;
    public static String PROVIDE_LNAME;
    public static String PROVIDE_DOB;
    public static String PROVIDE_PH_NO;
    public static String PROVIDE_VALID_PH_NO;
    public static String PROVIDE_CONFIRM_PASS;
    public static String CONFIRM_PASS_NOT_MATCHED;
    public static String PROVIDE_ADDRESS;
    public static String PROVIDE_PROVINCE;
    public static String PROVIDE_CITY;
    public static String PROVIDE_COUNTRY;
    public static String PROVIDE_VALID_ZIPCODE;
    public static String PROVIDE_COM_NAME;
    public static String PROVIDE_VAT_ID;
    public static String PROVIDE_LEGAL_MAIL;
    public static String PROVIDE_INVOICING_CODE;
    public static String REPLACE_CART;
    public static String RES_CLOSED_PRE_ORDER_LABEL;
    public static String RES_CLOSED_OPEN_AFETR_LABEL;
    public static String RES_CLOSED_LABEL;
    public static String PREORDER_ACCEPTED;
    public static String OPEN_NOW;
    public static String FREE_CUSOMIZATION;
    public static String PAID_CUSTOMIZATION;
    public static String ORDER_FROM;
    public static String CUSTOMIZE;
    public static String PROVIDE_DOOR_NO;
    public static String PROVIDE_STREET_ADD1;
    public static String PROVIDE_CITY_NAME;
    public static String PROVIDE_ZIP_CODE;
    public static String SELECT_COUNTRY_NAME;
    public static String PROVIDE_PROPER_CITY;
    public static String PROVIDE_PROPER_ZIP;
    public static String GEO_LOCATION_UNABLE;
    public static String UNABLE_TO_FIND_ADD;
    public static String ADDRESS_NOT_FOUNDED;
    public static String MONDAY;
    public static String TUESDAY;
    public static String WEDNESDAY;
    public static String THURSDAY;
    public static String FRIDAY;
    public static String SATURDAY;
    public static String SUNDAY;
    public static String PROVIDE_DEVLIERY_ADD;
    public static String REPLACE_CART_ITEM;
    public static String WANT_TO_REORDER;
    public static String WANT_TO_REORDER1;
    public static String WANT_TO_REORDER2;
    public static String YES_LABEL;
    public static String NO_LABEL;
    public static String OFFLINE;
    public static String ONLINE;
    public static String REMOVE_FROM_FAV;
    public static String NO_IN_FAV;
    public static String TERMS_AND_CONDITIONS;
    public static String AND;
    public static String COOKIES_POLICY;
    public static String PROVIDE_VAILD_NUMBER;
    public static String PROVIDE_VAILD_NAME;
    public static String PROVIDE_MSG;
    public static String PROVIDE_CONTACT_NO;
    public static String CONFIRM;
    public static String SUBMIT_DETAIL;
    public static String ORDER_NOTIFICATION;
    public static String NEWS_AND_OFFERS;
    public static String EMAIL_NOTIFICATION;
    public static String WENT_WRONG;
    public static String TOTAL_PAYABLE_AMT;
    public static String DELIVERY_TIME;
    public static String RES_CLOSED_DELIVERY_TIME;
    public static String PROVIDE_PAYMENT_TYPE;
    public static String PROVIDE_CARD;
    public static String PROVIDE_DELIVERY_TIME;
    public static String PROVIDE_CARD_TYPE;
    public static String PROVIDE_CVV_CODE;
    public static String PROVIDE_EXPIRY_YEAR;
    public static String PROVIDE_EXPIRY_MONTH;
    public static String PROVIDE_CARD_NO;
    public static String SELECT_EXP_MONTH;
    public static String SELECT_EXP_YEAR;
    public static String INSTALL_INSTA_APP;
    public static String MENU;
    public static String PRODUCT_LIST;
    public static String ALL_ENABLE_DISABLE;
    public static String ITEMS;
    public static String ITEM_DETAIL;
    public static String TYPE_OF_CUSINE;
    public static String SHOW_CUST;
    public static String CUSTOMIZATION;
    public static String PAST_ORDERS;
    public static String ORDER_SUCCESS;
    public static String ORDER_SUCCESS_DESC;
    public static String CONTINUE_SHOPPING;
    public static String CANCEL_NOTE;
    public static String DASHBOARD;
    public static String UPCOMING;
    public static String DECLINE;
    public static String DELIVER;
    public static String SCHEDULE;
    public static String HOLIDAY;
    public static String OPENING_TIME;
    public static String CLOSING_TIME;
    public static String REPLY;
    public static String PAYMENT_TYPE;
    public static String SELECT_TIME_ERROR;
    public static String SPE_NOTE;
    public static String ADD_ONS;
    public static String REMOVE;
    public static String TOTAL_AMT;
    public static String SCANNER;
    public static String SCAN_BARCODE;
    public static String ADD_POINT;
    public static String CUST_INFO;
    public static String ENTER_MANGALS;
    public static String NOTIFICATION;
    public static String SUPPORT;
    public static String SEND_QUERY_TEAM;
    public static String SEND;
    public static String WRITE_QUERY_HERE;
    public static String PROFILE;
    public static String CHANGE_PASS;
    public static String OLD_PASS;
    public static String NEW_PASS;
    public static String DELIVERY_TYPE_LATER;
    public static String DELIVERY_TYPE_NOW;
    public static String CASH_ON_DELIVERY;
    public static String CASH;
    public static String ACCEPTED;
    public static String CANCELLED;
    public static String PROVIDE_OLD_PASS;
    public static String PROVIDE_NEW_PASS;
    public static String PASS_NOT_MATCH;
    public static String SCANNING;
    public static String PROVIDE_MANGALS;
    public static String OUR_MENU;
    public static String CART_CONTAIN;
    public static String CART_DISCARD;
    public static String ITEM_CUST;
    public static String ADD_CUST;
    public static String ANOTHER_ITEM;
    public static String RED_ADD;
    public static String OPEN_CLOSE;
    public static String FAV;
    public static String NO_ITEM_FND;
    public static String SELECT_RATING_TYPE;
    public static String ENTER_COMMENT;
    public static String CHANGE_COMPANY;
    public static String CHANGE_ADDRESS;
    public static String ADD_CUTLERY;
    public static String CHOOSE_OPT;
    public static String CAMERA;
    public static String CANCEL;
    public static String CLOSE;
    public static String SELECT_LANG;
    public static String RATE_NOW;
    public static String PROVIDE_COMMENT;
    public static String NOW;
    public static String NAME;
    public static String RES_ADDRESS;
    public static String AVAILABLE_MANGAL;
    public static String REDEEM_MANGAL;
    public static String PAY_CARD;
    public static String ORDER_NOT_FND;
    public static String ACCEPT;
    public static String REASON;
    public static String PROD_NOT_AVAIL;
    public static String RES_CLOSED;
    public static String INGREDIENT;
    public static String TOTAL_COMP_ORDER;
    public static String TOTAL_COMP_ORDER_PRICE;
    public static String TOTAL_DECLINE_ORDER;
    public static String TOTAL_DECLINE_ORDER_PRICE;
    public static String SELECT;
    public static String STREET;
    public static String BUILDING_NO;
    public static String RES_WEBSITE;
    public static String PROVIDE_CONF_PASS;
    public static String ALLERGENS;
    public static String WRONG_PASS_MSG;
    public static String WRONG_EMAIL_MSG;
    public static String PROVIDE_NAME;
    public static String ENTER_REQUIRED_FIELD_MSG;
    public static String LANG_FOUNDED_MSG;
    public static String UNAUTH_ACCESS_MSG;
    public static String LANG_NOT_FOUNDED_MSG;
    public static String LOCATION_PERMISSION;
    public static String LANG_SET_MSG;
    public static String SOMETHING_WRONG_MSG;
    public static String CART_UPDATED_MSG;
    public static String ITEM_REMOVE_FROM_CART_MSG;
    public static String OFFER_FOUNDED_MSG;
    public static String OFFER_NOT_FOUNDED_MSG;
    public static String RES_NOT_NEAR_YOU_MSG;
    public static String ITEM_ADD_FAV_MSG;
    public static String ALREADY_FAV_MSG;
    public static String ITEM_REMOVE_FAV_MSG;
    public static String ITEM_NOT_IN_FAV_MSG;
    public static String ITEM_NOT_FOUNDED_MSG;
    public static String APPLY_SUCCESS_MSG;
    public static String NOT_ENOUGH_MANGALS_MSG;
    public static String ITEM_FOUNDED_MSG;
    public static String CART_EMPTY_MSG;
    public static String SUCCESS_MSG;
    public static String PAYMENT_METHOD_INVALID_MSG;
    public static String CART_NOT_EXIST_MSG;
    public static String ADDED_IN_CART_MSG;
    public static String SOMETHING_NOT_ADDED_IN_CART_MSG;
    public static String NOT_ADDED_IN_CART_MSG;
    public static String CART_NOT_FOUND_MSG;
    public static String ITEM_NO_LONGER_AVA_MSG;
    public static String ITEM_MISMATCH_RES_MSG;
    public static String RES_CLOSE_MSG;
    public static String RES_FOUNDED_MSG;
    public static String RES_NOT_FOUNDED_MSG;
    public static String COM_NOT_CREATE_MSG;
    public static String USER_NOT_REG_MSG;
    public static String USER_ALREADY_EXIST_MSG;
    public static String PRO_UPDATED_MSG;
    public static String ITEM_NOT_AVA_MSG;
    public static String NOT_ANY_FAV_MSG;
    public static String ORDER_FOUNDED_MSG;
    public static String ORDER_NOT_FOUNDED_MSG;
    public static String ALREADY_SHARE_MSG;
    public static String INVALID_SHARE_MSG;
    public static String CART_FOUNDED_MSG;
    public static String CART_NOT_FOUNDED;
    public static String CARD_ADDED_MSG;
    public static String CARD_NOT_ADDED_MSG;
    public static String CARD_SET_MSG;
    public static String CARD_NOT_FOUNDED_MSG;
    public static String LOGOUT_MSG;
    public static String LOGOUT_CONFIRM;
    public static String RECORD_NOT_FOUNDED_MSG;
    public static String RATING_ADDED_MSG;
    public static String CONTACT_SUB_MSG;
    public static String QUE_ALREADY_MSG;
    public static String DEV_TOKEN_ADDED_MSG;
    public static String QUE_NOT_FOUNDED;
    public static String QUE_FOUNDED;
    public static String MAIL_SENT_MSG;
    public static String USER_NOT_EXIST_EMAIL_MSG;
    public static String PAGE_FOUNDED_MSG;
    public static String PAGE_NOT_FOUNDED;
    public static String STATUS_CHANGED_MSG;
    public static String INVALID_NOTI_MSG;
    public static String ADD_UPDATED_MSG;
    public static String COM_DETAIL_UPDATED_MSG;
    public static String IMG_FOUNDED_MSG;
    public static String IMG_NOT_FOUNDED_MSG;
    public static String ADD_SAVED_MSG;
    public static String ADD_FOUNDED_MSG;
    public static String ADD_NOT_FOUNDED_MSG;
    public static String ADD_SET_MSG;
    public static String THANK_FOR_FEEDBACK_MSG;
    public static String ALREADY_REVIEW_MSG;
    public static String REVIEW_FOUNDED_MSG;
    public static String REVIEW_NOT_FOUNDED_MSG;
    public static String ITEM_FOUNDED_IN_CAT_MSG;
    public static String ORDER_STATUS_CHANGED_MSG;
    public static String ORDER_ACCEPTED_MSG;
    public static String ORDER_DECLINED_MSG;
    public static String ORDER_PREAPRED_MSG;
    public static String ORDER_DELIVERED_MSG;
    public static String POINTS_ADDED_MSG;
    public static String USER_NOT_FOUNDED;
    public static String CAT_FOUNDED;
    public static String CAT_NOT_FOUNDED_MSG;
    public static String USER_FOUNDED_MSG;
    public static String REPLY_ADDED_MSG;
    public static String ITEM_STATUS_CHANGED;
    public static String INVALID_STATUS;
    public static String TIME_CHANGED_MSG;
    public static String UNAUTH_ORDER_ACCESS_MSG;
    public static String LOGIN_SUCCESS_MSG;
    public static String HOLIDAY_FOUNDED_MSG;
    public static String HOLIDAY_NOT_FOUNDED_MSG;
    public static String TICKET_GEN_MSG;
    public static String ITEM_CUST_FOUNDED_MSG;
    public static String ITEM_CUST_NOT_FOUNDED_MSG;
    public static String PASS_CHANGED__MSG;
    public static String HOLIDAY_ADDED_MSG;

    public static String BOOK_A_TABLE;
    public static String ADD_A_NEW_RESERVATION;
    public static String APPROVED;
    public static String REJECT;
    public static String CANCEL_BOOKING;
    public static String SEARCH;
    public static String ABOUT;
    public static String CHOOSE_YOUR_TIME;
    public static String NUMBER_OF_GUEST;
    public static String SET_BOOKING;
    public static String BOOK_TABLE;
    public static String TABLE_BOOKING;
    public static String SPACE_AVAILABLE;
    public static String REJECT_TABLE_RESERVATION;
    public static String PLEASE_WRITE_REJECTION_MESSAGE;
    public static String WRITE_YOUR_QUERY_HERE;
    public static String DINNER;
    public static String LUNCH;
    public static String CANCEL_RESERVATION;
    public static String ARRIVED;
    public static String LEFT;
    public static String SPECIAL_REQ;
    public static String WRITE_SPECIAL_REQ;
    public static String SEATS_LEFT;
    public static String TODAY_TABLE_BOOKING;
    public static String NEW;
    public static String ORDERS;
    public static String ONGOING;
    public static String TABLE_NOT_FOUND;
    public static String STATUS;
    public static String CURRENT;
    public static String BOOKING_TYPE;
    public static String ALL_SERVICE;
    public static String SELECT_SERVICE;
    public static String RESERVED;
    public static String CANCELLATION_NOTE;
    public static String NEW_BOOKING_RECEIVED;
    public static String BOOKING_HAS_BEEN_ACCEPTED;
    public static String CUSTOMER_HAS_BEEN_ARRIVED;
    public static String CUSTOMER_HAS_BEEN_LEFT;
    public static String BOOKING_HAS_BEEN_REJECTED;




}